name: Package

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish to NuGet.org

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - uses: nuget/setup-nuget@v1
        name: Setup NuGet
        with:
          nuget-version: '6.x'

      - name: Build Domain dll
        run: dotnet build -c Release ./src/Domain/Domain.csproj -o ./src/Domain/app/bin

      - name: Create Domain package
        run: nuget pack ./src/Domain/Domain.nuspec
        
      - name: Publish Domain package
        run: nuget push LanzDev.CleanArchitecture.Libraries.Domain.*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
        
      - name: Build Application dll
        run: dotnet build -c Release ./src/Application/Application.csproj -o ./src/Application/app/bin
        
      - name: Create Application package
        run: nuget pack ./src/Application/Application.nuspec

      - name: Publish Application package
        run: nuget push LanzDev.CleanArchitecture.Libraries.Application.*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate